# Generated by Django 5.2 on 2025-05-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='paymnet_method',
            new_name='payment_method',
        ),
    ]
