# Generated by Django 5.2 on 2025-04-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_showtimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.CharField(blank=True, max_length=100, null=True)),
                ('row_label', models.CharField(max_length=10)),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('VIP', 'VIP'), ('Regular', 'Regular')], max_length=10)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.theaters')),
            ],
        ),
    ]
