# Generated by Django 5.2 on 2025-04-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller')], max_length=250)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam')], max_length=100)),
                ('synopsis', models.TextField()),
                ('cast', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('release_date', models.DateField()),
                ('triller_url', models.CharField(blank=True, max_length=2500, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
