# Generated by Django 5.2 on 2025-04-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
