# Generated by Django 5.2 on 2025-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_name',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images/'),
        ),
    ]
